[package]
name = "hello_ntp"
version = "0.1.0"
edition = "2021"


[dependencies]
rsntp = { version = "4.0.0", default-features = false, features = ["chrono"]  }
chrono = "*"

reqwest = { version = "0.11", features = ["blocking"] }